### ISSUE TITLE
AemReact is not defined 

### ISSUE THREAD

**Issue by JimmyLv** [sinnerschrader/aem-react#8]
```

An error has occured during execution of the selected action: AemReact is not defined -> ReferenceError: AemReact is not defined
    at constructor.eval (eval at <anonymous> (http://localhost:4505/libs/cq/gui/components/authoring/editors/clientlibs/core.js:1917:23), <anonymous>:1:13)
    at constructor.handleEvent (http://localhost:4505/libs/cq/gui/components/authoring/editors/clientlibs/core.js:19321:41)
    at HTMLDivElement.dispatch (http://localhost:4505/etc/clientlibs/granite/jquery.js:4665:9)
    at HTMLDivElement.elemData.handle (http://localhost:4505/etc/clientlibs/granite/jquery.js:4333:28)

```

**Comment by stemey** [comment]
You are missing the author mode javascript. It is currently in the demo content package only: https://github.com/sinnerschrader/aem-react/tree/master/demo/src/main/content/jcr_root/etc/designs/react-demo/js/react-cq

I am thinking about integrating it in aem-react-js.

**Comment by stemey** [comment]
I think you are trying the demo in Touch UI. Touch UI support is very limited in 0.2.0
